#define IO_ISRLOC 0x00, IO_READWRITE
#define IO_IRQSRC 0x01, IO_READWRITE
#define IO_ENVCMD 0x02, IO_WRITEONLY

#define IO_DBGCON  0x10, IO_READWRITE
#define IO_TTYCON  0x11, IO_READONLY
#define IO_TTYREQ  0x12, IO_READWRITE
#define IO_TTYDATA 0x13, IO_READWRITE
#define IO_TTYSTAT 0x14, IO_READWRITE
